import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
import { renderBrandedEmail } from "../_shared/branded-email.ts";
import { buildSignupAlertContext, buildSignupDeliveryUpdate, isDuplicateSignupAlertError } from "../_shared/signup-alert.ts";

const corsHeaders = { "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS", "Access-Control-Allow-Origin": "*" };
const json = (body: Record<string, unknown>, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });
const asString = (value: unknown) => typeof value === "string" ? value.trim() : "";
const escapeHtml = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");

const sendEmail = async ({ fromAddress, html, recipients, resendApiKey, subject, text }: { fromAddress: string; html: string; recipients: string[]; resendApiKey: string; subject: string; text: string }) => {
  const response = await fetch("https://api.resend.com/emails", { method: "POST", headers: { Authorization: `Bearer ${resendApiKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ from: fromAddress, to: recipients, subject, html, text }) });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof payload?.message === "string" ? payload.message : "The email provider rejected the alert.");
  return typeof payload?.id === "string" ? payload.id : null;
};

Deno.serve(async (request) => {
  if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders });
  if (request.method !== "POST") return json({ error: "Method not allowed." }, 405);
  let adminClient: ReturnType<typeof createClient> | null = null;
  let signupEventId = "";
  try {
    const payload = await request.json().catch(() => ({})) as Record<string, unknown>;
    const userId = asString(payload.userId);
    const plan = asString(payload.plan);
    if (!userId || !["starter", "growth", "business"].includes(plan)) return json({ error: "A valid signup context is required." }, 400);

    const supabaseUrl = Deno.env.get("SUPABASE_URL")?.trim() ?? "";
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")?.trim() ?? "";
    const resendApiKey = Deno.env.get("RESEND_API_KEY")?.trim() ?? "";
    const fromAddress = Deno.env.get("EMAIL_FROM_ADDRESS")?.trim() ?? "";
    const recipients = (Deno.env.get("SIGNUP_ALERT_RECIPIENTS") || "foxyrule@gmail.com,admin@moniger.net").split(",").map((item) => item.trim().toLowerCase()).filter(Boolean);
    if (!supabaseUrl || !serviceRoleKey || !resendApiKey || !fromAddress || recipients.length === 0) return json({ error: "Signup alert delivery is not configured." }, 500);

    adminClient = createClient(supabaseUrl, serviceRoleKey, { auth: { persistSession: false } });
    const userResponse = await adminClient.auth.admin.getUserById(userId);
    if (userResponse.error || !userResponse.data.user) return json({ error: "Signup account was not found." }, 404);
    const user = userResponse.data.user;
    const metadata = user.user_metadata ?? {};
    const email = (user.email || "").trim().toLowerCase();
    const context = buildSignupAlertContext({
      email,
      emailConfirmedAt: user.email_confirmed_at,
      environment: Deno.env.get("APP_ENVIRONMENT")?.trim() || "production",
      plan,
      userId,
      userMetadata: metadata,
    });

    const insertResponse = await adminClient.from("signup_alert_events").insert({ auth_user_id: user.id, email: context.email, full_name: context.fullName, business_name: context.businessName, plan: context.plan, signup_status: context.signupStatus, environment: context.environment }).select("id").single();
    if (insertResponse.error) {
      if (isDuplicateSignupAlertError(insertResponse.error.code)) return json({ ok: true, duplicate: true });
      throw insertResponse.error;
    }
    signupEventId = insertResponse.data.id;

    const planLabel = context.plan.charAt(0).toUpperCase() + context.plan.slice(1);
    const emailContent = renderBrandedEmail({ subject: `New ${planLabel} signup on Moniger`, preheader: `${context.businessName} created a Moniger account`, heading: `New ${planLabel} signup`, bodyHtml: `<p><strong>Business:</strong> ${escapeHtml(context.businessName)}</p><p><strong>Contact:</strong> ${escapeHtml(context.fullName)} &lt;${escapeHtml(context.email)}&gt;</p><p><strong>Status:</strong> ${escapeHtml(context.signupStatus.replace(/_/g, " "))}</p><p><strong>Plan:</strong> ${escapeHtml(planLabel)}</p><p><strong>Signed up:</strong> ${escapeHtml(new Date().toISOString())}</p>`, footerText: "This alert was generated by Moniger signup monitoring." });
    const providerMessageId = await sendEmail({ ...emailContent, fromAddress, recipients, resendApiKey });
    await adminClient.from("signup_alert_events").update(buildSignupDeliveryUpdate({ providerMessageId })).eq("id", signupEventId);
    return json({ ok: true });
  } catch (error) {
    if (adminClient && signupEventId) {
      await adminClient.from("signup_alert_events").update({ delivery_status: "failed", failure_reason: error instanceof Error ? error.message : "Unknown delivery error" }).eq("id", signupEventId);
    }
    return json({ error: error instanceof Error ? error.message : "Unable to send signup alert." }, 500);
  }
});
