// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { createAuthStorage } from './auth-storage';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_REQUEST_TIMEOUT_MS = 15_000;
const SUPABASE_MUTATION_TIMEOUT_MS = 30_000;

export class SupabaseMutationOutcomeUnknownError extends Error {
  constructor() {
    super("The request timed out after it was sent. Its server-side outcome is unknown; check the result before retrying.");
    this.name = "SupabaseMutationOutcomeUnknownError";
  }
}

export const fetchWithTimeout: typeof fetch = async (input, init) => {
  if (init?.signal?.aborted) {
    throw init.signal.reason ?? new DOMException("The request was aborted.", "AbortError");
  }

  const controller = new AbortController();
  const method = (init?.method ?? "GET").toUpperCase();
  const isMutation = !["GET", "HEAD", "OPTIONS"].includes(method);
  let timedOut = false;
  const timeoutId = window.setTimeout(() => {
    timedOut = true;
    controller.abort();
  }, isMutation ? SUPABASE_MUTATION_TIMEOUT_MS : SUPABASE_REQUEST_TIMEOUT_MS);
  const abortRequest = () => controller.abort();

  init?.signal?.addEventListener("abort", abortRequest, { once: true });

  try {
    return await fetch(input, { ...init, signal: controller.signal });
  } catch (error) {
    if (timedOut && isMutation) {
      throw new SupabaseMutationOutcomeUnknownError();
    }
    throw error;
  } finally {
    window.clearTimeout(timeoutId);
    init?.signal?.removeEventListener("abort", abortRequest);
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createAuthStorage(),
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: fetchWithTimeout,
  },
});
